package co.unicauca.restauranteonline.presentacion;

import co.unicauca.restauranteonline.client.access.Factory;
import co.unicauca.restauranteonline.client.access.IAlmuerzoAccess;
import co.unicauca.restauranteonline.client.domain.services.ComponenteService;
import static co.unicauca.restauranteonline.client.infra.Messages.successMessage;
import co.unicauca.restauranteonline.commons.domain.Componente;
import java.sql.PreparedStatement;
import co.unicauca.restauranteonline.client.access.IComponentesAccess;
import co.unicauca.restauranteonline.client.domain.services.AlmuerzoService;
import co.unicauca.restauranteonline.commons.domain.Almuerzo;
import java.awt.Image;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SoftwareTeam
 *
 */
public class GUIAgregarAlmuerzo extends javax.swing.JFrame {

    /**
     * Creates new form GUAGREGARCOMPONENTE1
     */
    List<Componente> objListComponentes = new ArrayList<Componente>();
    String tipoid;
    
    public GUIAgregarAlmuerzo() throws Exception  {
        initComponents();
        setLocationRelativeTo(null); //centrar la ventana
        setTitle("Agregar componente");
        iniciar();
    }
    private void iniciar() throws Exception{
        mostrar();
        esconder();
        llenarcbx();
    }
    private void mostrarOpc() {
        if (cbxSelectTipo.getSelectedItem().toString().isEmpty()) {
            esconder();
        }
        if (cbxSelectTipo.getSelectedItem().toString() == "Entrada") {
            lblNombreCom.setVisible(true);
            cbxEntrada.setVisible(true);
            tipoid = "1";
        }
        if (cbxSelectTipo.getSelectedItem().toString() == "Principio") {
            lblTipoCom.setVisible(true);
            cbxPrincipio.setVisible(true);
            tipoid = "2";
        }
        if (cbxSelectTipo.getSelectedItem().toString() == "Proteina") {
            lblTipoCom1.setVisible(true);
            cbxProteina.setVisible(true);
            tipoid = "3";
        }
        if (cbxSelectTipo.getSelectedItem().toString() == "Bebida") {
            lblTipoCom2.setVisible(true);
            cbxBebida.setVisible(true);
            tipoid = "4";
        }
    }

    private void llenarcbx() {

        cbxSelectTipo.addItem("Entrada");
        cbxSelectTipo.addItem("Principio");
        cbxSelectTipo.addItem("Proteina");
        cbxSelectTipo.addItem("Bebida");
    }

    private void esconder() {
        btnCrearAlmu.setVisible(false);
        lblNombreCom.setVisible(false);
        cbxEntrada.setVisible(false);
        lblTipoCom.setVisible(false);
        cbxPrincipio.setVisible(false);
        lblTipoCom1.setVisible(false);
        cbxProteina.setVisible(false);
        lblTipoCom2.setVisible(false);
        cbxBebida.setVisible(false);
      

    }

    private String sacarIdComp() {
        switch (Integer.parseInt(tipoid)) {
            case 1:
                return buscarIdCom(cbxEntrada.getSelectedItem().toString());

            case 2:
                return buscarIdCom(cbxPrincipio.getSelectedItem().toString());

            case 3:
                return buscarIdCom(cbxProteina.getSelectedItem().toString());

            case 4:
                return buscarIdCom(cbxBebida.getSelectedItem().toString());

        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnAlm = new javax.swing.JPanel();
        lblAgregarCom = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombreCom = new javax.swing.JLabel();
        cbxEntrada = new javax.swing.JComboBox<>();
        lblTipoCom = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblTipoCom1 = new javax.swing.JLabel();
        lblTipoCom2 = new javax.swing.JLabel();
        txtIdAlm = new javax.swing.JTextField();
        btnSeleccionarImg = new javax.swing.JButton();
        cbxProteina = new javax.swing.JComboBox<>();
        cbxBebida = new javax.swing.JComboBox<>();
        cbxPrincipio = new javax.swing.JComboBox<>();
        btnCrearAlmu = new javax.swing.JToggleButton();
        cbxSelectTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgregarCom.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblAgregarCom.setText("AGREGAR ALMUERZO");

        lblId.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblId.setText("Id Almuerzo");

        lblNombreCom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNombreCom.setText("Entrada");

        cbxEntrada.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntradaActionPerformed(evt);
            }
        });

        lblTipoCom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTipoCom.setText("Principio");

        btnAtras.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras3.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblTipoCom1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTipoCom1.setText("Proteina");

        lblTipoCom2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTipoCom2.setText("Bebida");

        txtIdAlm.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtIdAlm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnSeleccionarImg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSeleccionarImg.setText("Seleccionar imagen");
        btnSeleccionarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarImgActionPerformed(evt);
            }
        });

        cbxProteina.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxProteina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProteinaActionPerformed(evt);
            }
        });

        cbxBebida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBebidaActionPerformed(evt);
            }
        });

        cbxPrincipio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbxPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPrincipioActionPerformed(evt);
            }
        });

        btnCrearAlmu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearAlmu.setText("Crear");
        btnCrearAlmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlmuActionPerformed(evt);
            }
        });

        cbxSelectTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSelectTipoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Selecciona el tipo de componente");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_restaurante .png"))); // NOI18N

        javax.swing.GroupLayout jpnAlmLayout = new javax.swing.GroupLayout(jpnAlm);
        jpnAlm.setLayout(jpnAlmLayout);
        jpnAlmLayout.setHorizontalGroup(
            jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnAlmLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblAgregarCom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(85, 85, 85))
            .addGroup(jpnAlmLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnAlmLayout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdAlm))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnAlmLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbxSelectTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnAlmLayout.createSequentialGroup()
                                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreCom)
                                    .addComponent(lblTipoCom)
                                    .addComponent(lblTipoCom1)
                                    .addComponent(lblTipoCom2))
                                .addGap(18, 18, 18)
                                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxPrincipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxProteina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnAlmLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btnSeleccionarImg))
                            .addGroup(jpnAlmLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnAlmLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrearAlmu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)))))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jpnAlmLayout.setVerticalGroup(
            jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAlmLayout.createSequentialGroup()
                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblAgregarCom))
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addGap(36, 36, 36)
                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAlm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(btnCrearAlmu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSelectTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCom))
                        .addGap(14, 14, 14)
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCom)
                            .addComponent(cbxPrincipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCom1)
                            .addComponent(cbxProteina, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoCom2)
                            .addComponent(cbxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnAlmLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSeleccionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(jpnAlmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jpnAlm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnAlm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        GUIAdmin admin = new GUIAdmin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        IAlmuerzoAccess service = Factory.getInstance().getAlmuerzoService();

        AlmuerzoService almService = new AlmuerzoService(service);

        Almuerzo objAlm = new Almuerzo();

        //  IComponentesAccess service= Factory.getInstance().getComponenteService();
//        ComponenteService componenteService= new ComponenteService(service);
        Componente componente = new Componente();

        objAlm.setIdAlmuerzo(txtIdAlm.getText());
        objAlm.setComp(sacarIdComp());
        objAlm.setIdComp(tipoid);

        try {
            String response = almService.createAlmuerzo(objAlm);
            successMessage("Almuerzo " + response + " agregado con exito.", "Atención");
            clearCotronls();

        } catch (Exception ex) {
            System.out.println(ex);
            successMessage(ex.getMessage() + "Error", "Atención");
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSeleccionarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImgActionPerformed
        // TODO add your handling code here:

        String Ruta = "";
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JGP, PNG & GIF", "jpg", "png", "gif");
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            Ruta = jFileChooser.getSelectedFile().getPath();
            
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
            lblImagen.setIcon(mIcono); 
            
        }
    }//GEN-LAST:event_btnSeleccionarImgActionPerformed

    private void cbxPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPrincipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPrincipioActionPerformed

    private void cbxBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBebidaActionPerformed

    private void cbxProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProteinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProteinaActionPerformed

    private void cbxEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntradaActionPerformed

    private void btnCrearAlmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlmuActionPerformed
        // TODO add your handling code here:
        IAlmuerzoAccess service = Factory.getInstance().getAlmuerzoService();

        AlmuerzoService almService = new AlmuerzoService(service);

        Almuerzo objAlm = new Almuerzo();

        objAlm.setIdAlmuerzo(txtIdAlm.getText());
        objAlm.setRestId("1");
        objAlm.setCostoAlm("10000");
        try {
            String response = almService.createAlmuerzoID(objAlm);
            successMessage("Almuerzo " + response + " agregado con exito.", "Atención");
            clearCotronls();

        } catch (Exception ex) {
            System.out.println(ex);
            successMessage(ex.getMessage() + "Error", "Atención");
        }

    }//GEN-LAST:event_btnCrearAlmuActionPerformed

    private void cbxSelectTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSelectTipoActionPerformed
        // TODO add your handling code here:
        esconder();
        mostrarOpc();
    }//GEN-LAST:event_cbxSelectTipoActionPerformed
    private void clearCotronls() {

        txtIdAlm.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarAlmuerzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUIAgregarAlmuerzo().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(GUIAgregarAlmuerzo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public String buscarIdCom(String parItem) {

        for (int i = 0; i < objListComponentes.size(); i++) {
            if (parItem.equals(objListComponentes.get(i).getNombreComponente())) {
                return objListComponentes.get(i).getIdComponente() + "";
            }
        }
        return "";

    }

    public void mostrar() throws Exception  {
        IComponentesAccess service = Factory.getInstance().getComponenteService();
        ComponenteService componenteService = new ComponenteService(service);

        Componente objComponente = new Componente();

        objListComponentes = componenteService.listComponentes();

        for (int i = 0; i < objListComponentes.size(); i++) {

            if ("Entrada".equals(objListComponentes.get(i).getTipoComponente())) {
                String componenteMenu = objListComponentes.get(i).getNombreComponente();
                cbxEntrada.addItem(componenteMenu);

            }
            if ("Principio".equals(objListComponentes.get(i).getTipoComponente())) {
                String componenteMenu = objListComponentes.get(i).getNombreComponente();
                cbxPrincipio.addItem(componenteMenu);
            }
            if ("Proteina".equals(objListComponentes.get(i).getTipoComponente()) || "Proteína".equals(objListComponentes.get(i).getTipoComponente())) {
                String componenteMenu = objListComponentes.get(i).getNombreComponente();
                cbxProteina.addItem(componenteMenu);
            }
            if ("Bebida".equals(objListComponentes.get(i).getTipoComponente())) {
                String componenteMenu = objListComponentes.get(i).getNombreComponente();
                cbxBebida.addItem(componenteMenu);
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JToggleButton btnCrearAlmu;
    private javax.swing.JButton btnSeleccionarImg;
    private javax.swing.JComboBox<String> cbxBebida;
    private javax.swing.JComboBox<String> cbxEntrada;
    private javax.swing.JComboBox<String> cbxPrincipio;
    private javax.swing.JComboBox<String> cbxProteina;
    private javax.swing.JComboBox<String> cbxSelectTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpnAlm;
    private javax.swing.JLabel lblAgregarCom;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreCom;
    private javax.swing.JLabel lblTipoCom;
    private javax.swing.JLabel lblTipoCom1;
    private javax.swing.JLabel lblTipoCom2;
    private javax.swing.JTextField txtIdAlm;
    // End of variables declaration//GEN-END:variables
}
